server:
  port: 8082

spring:
  application:
    name: demo-redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # Redis服务器连接密码（默认为空）,无密码需注释，可能报错ERR Client sent AUTH, but no password is set
      #password:
      jedis:
        pool:
          #连接池中的最小空闲连接
          min-idle: 0
          #连接池中的最大空闲连接
          max-idle: 8
          #最大活动连接
          max-active: 100
          #连接池最大阻塞等待时间毫秒（使用负值表示没有限制)
          max-wait: 6000